### ISSUE TITLE
[Bug]: Gobuster

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#416] opened 2023-11-14 09:10 UTC
### Name of Bug

Error message when execute

### What Happened?

Execute command in DDT product error message

### Steps to Reproduce

Refer to the Report

**Comment by v-xl** [comment] 2023-11-26 05:31
Testing out the tool, I can straight away see an issue:	
 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/4e32de03-28e8-402f-8953-2e9a612d161d)

The program isn’t executing when we click the ‘Start Brute-Forcing’ button.

After looking through the tauri.conf.json file I can see that the gobuster tool is included in the shell scope, however the ‘G’ is capitalised which is the cause of the issue, since the command itself should be executed in all lower case.
 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/e372da33-1ef0-4db6-a02b-82532452a143)

After modifying this to a lowercase ‘g’, and saving the file, I proceed to test again.
 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/19e6e9a8-6166-4f3a-baab-c20bf9c6f416)

The command now executes successfully, however there is a new error message:
 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/4e46b9e0-8f98-4511-b97d-3f73cf5eaed0)

When trying to run the command in the console directly we are told that the tool isn’t currently installed.
 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/52849885-71ce-4f9c-a52d-23fd98808b11)

I believe this should be resolved as part of feature request #423.

After installing it manually, the tool will now run almost as intended.
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/5741344e-614c-4314-a6e3-40e063595dc0)

The output file cannot be found.
Looking at the code, ‘SaveOutputToTextFile’ function had not been implemented for the GoBuster tool.

I’ve modified the code to remove the existing ‘Output file’ textbox, and implemented the SaveOutputToTextFile_v2 function. All is working as intended after testing.
 ![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/86a2a19f-a112-4eaf-9994-a0d19183edd0)

After clicking “Start” the command will complete, and we then have the option to save the file.
 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/5c77c475-e66f-4fea-838a-f860a23bd522)


This was successful:  
 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/6c9d8302-b1bd-4546-85f2-8fce2ccde237)
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/140072961/a1a3ea87-b5d3-4177-86e9-7dcaffc7e2bc)

**Comment by bradleybogg** [comment] 2023-11-27 05:02
Thanks @v-xl for linking #423.
When pull (https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/pull/433) is merged please modify dependencies.json

Cheers

**Closed** 2023-12-13 11:30 UTC
Labels: bug
